### ISSUE TITLE
add `flash_update_data` function

### ISSUE THREAD

**Issue by willwerscheid** [willwerscheid/flashier#100]
as discussed with @stephens999: keep gl, ql, etc. (so do not need to update KL terms) but update Y and other data objects and also update R2, tau, ELBO, and any other calculations that depend on the data

**Comment by stephens999** [comment]
@willwerscheid  can i bump this now flashier is submitted? Should be easy?

**Comment by willwerscheid** [comment]
this is now done as part of the GBCD workflow
