### ISSUE TITLE
intro to flashier vignette needs update?

### ISSUE THREAD

**Issue by dzemmour** [willwerscheid/flashier#130]
Hi,

It looks like the vignette uses an older version of flashier (1.0.23) and the plotting function doesn't work with the 1.0.53 version. https://willwerscheid.github.io/flashier/articles/flashier_intro.html

Thanks!
David

**Comment by pcarbo** [comment]
@dzemmour Thanks for pointing this out. I've updated this vignette and the other pages for flashier 1.0.53. However the plot() function should still work with the latest version of flashier. If you are still getting an error, could you give more details about the error message you are getting, and what you ran exactly to generate the error?

**Comment by pcarbo** [comment]
Also, if this fixed your problem, could you please close this issue? Thank you.

**Comment by dzemmour** [comment]
Thanks!
