### ISSUE TITLE
Clarifying behavior with fixed factors

### ISSUE THREAD

**Issue by suzannastep** [willwerscheid/flashier#70]
It would be nice to clarify the documentation, and perhaps even allow the user to change behavior if they want the opposite functionality.

First, when a factor is fixed to certain values at certain spots, do those values contribute to the estimation of the prior? Or are fixed values ignored when estimating priors? This was unclear to me in tree-based EBMF code where I was manually fixing spots to be zero in order to enforce hierarchical constraints. I was unsure if those fixed zeros contributed to a point mass at zero in the prior estimate. I think in many cases people won't want fixed values to contribute to a prior estimate, or at least that was the behavior I was expecting. However, you could imagine that fixed values might come from a user who wants to incorporate those values into an estimation of the prior and would want the opposite behavior.

Second, it would be nice to clarify in the documentation that if a factor is fixed, then it will still be fixed in the final flash object, and backfitting will not change those values. I had a scenario in working with internal tree data where I wanted to play with fixing values in factors using hierarchical constraints as I went, but wanted to relax those constraints and backfit at the end. When I tried to backfit, nothing changed because everything was fixed.

**Comment by willwerscheid** [comment]
There is a field in the `flash.fit` object called `use.fixed.to.est.g` that's set to `FALSE` when the `flash.fit` object is initialized. If you want to experiment you could manually toggle that field. It's a global setting though -- you can't have different behavior for different factors. I will update the docs to explain this default behavior but it would take some care to make the behavior easily modifiable by a user. I'll keep the issue open and think about how (and whether) I'd like to do that.

I'll also make the docs more clear for the second issue. You can "unfix" loadings by setting `is.fixed = FALSE`. It's explained in the `is.fixed` parameter description but maybe that's too difficult for users to find -- I can say something in the general description as well.

**Comment by willwerscheid** [comment]
Accidentally closed this -- would you mind taking a look at the changes @suzannastep and letting me know whether you think this will do?

**Comment by suzannastep** [comment]
This is perfect! Thank you!
