### ISSUE TITLE
Explain what init.fn.default does

### ISSUE THREAD

**Issue by pcarbo** [willwerscheid/flashier#73]
Please explain in the help pages what `init.fn.default` does. Currently there is a help page for `init.fn.default` but it doesn't actually say what it does. For example, `maxiter` specifies the maximum number of iterations, but doesn't say of what. (Jason says: "The details are in my thesis, chapter 2.2.3. In brief, it’s just an implementation of the power method but can handle missing data.")

**Comment by willwerscheid** [comment]
fixed
