### ISSUE TITLE
Error from init.fn.softImpute

### ISSUE THREAD

**Issue by jean997** [willwerscheid/flashier#78]
Using `flash.add.greedy` to add factors with `init.fn = flashier:::init.fn.softImpute` gives the error

```
Error in fitted.flash.fit(flash) : 
  Flash object does not have any factors
 ```

**Comment by willwerscheid** [comment]
need to rewrite init.fn.softImpute to handle flash objects with no factors. in that case do not call fitted.flash.fit but pass the data in directly

**Comment by willwerscheid** [comment]
also should be residuals.flash.fit not fitted.flash.fit!

**Comment by willwerscheid** [comment]
this appears to have been fixed in december 2022
