### ISSUE TITLE
Problem when using `flashier` to filling in missing values

### ISSUE THREAD

**Issue by zq2209** [willwerscheid/flashier#80]
# Issue
I am tring to fill in missing values in phenotype martix. I have tried both `flashr` and `flashier` packages. `flashr` works well for me. But I met blocker when I use `flashier`. 

Here is an example that help me illustrate my problem.

# Generating minimum working example

```
set.seed(1)
n = 100
p = 500
k = 7
LL = matrix(rnorm(n*k),nrow=n)
FF = matrix(rnorm(p*k),nrow=p)
Y = LL %*% t(FF) + rnorm(n*p)
# Assign some missing values
Ymiss=Y
Ymiss[1:20,1] = NA
```
# Use `flashr` to fill in missing values
```
library(flashr)
f1 = flashr::flash(Ymiss)
Ynew = flashr::flash_fill(Ymiss,f1)
```
f1 is generated by calling flash function in `flashr`.    
According the [vignette of flashr](https://stephenslab.github.io/flashr/articles/flash_intro.html), I can simply call ` flash_fill` to fill in missing values by using `f1`. 

# Codes for using `flashier`

```
library(flashier)
f2 = flashier::flash(Ymiss)
```
The blocker appeared after generating f2. I tried to call a function in `flashier` to fill in the missing values by using `f2`, just like what I did for `flashr`. But I didn't find any proper function in `flashier` package. It seems like such `flashier::flash_fill` function doesn't exist in `flashier`.

## Attempt
I have read through the vignette and all functions in `flashier` function, I failed to find some information to help me fill in missing values. And I didn't come up with some effective ways to use `f2` to fill in missing values.     
So I might need some help on this.

**Comment by gaow** [comment]
@zq2209 could you post here a minimal working example with the exact code you used for both `flashr` (that you succeeded) as well as `flashier` (that did not work) to help answer your question?

**Comment by zq2209** [comment]
I have updated the issue with the working example and codes. Thanks.

**Comment by willwerscheid** [comment]
Hi @zq2209 . Sorry to have missed this when it was first posted. I hope it is not too late for me to be of some help. Could you please explain what you mean by "blocker"? I ran the code above on the current version of `flashier` and I got 7 factors (as expected). I did not include a `flash_fill()` function in `flashier` but you can easily impute missing values using method `fitted()`. For example:
```
Yfill <- ifelse(is.na(Ymiss), fitted(f2), Ymiss)
```

**Comment by zq2209** [comment]
Thanks so much for your help! That helped me solve the problem.
