### ISSUE TITLE
Remove verbose = 0 in flash calls in vignettes

### ISSUE THREAD

**Issue by pcarbo** [willwerscheid/flashier#94]
In the vignettes, I think it is helpful to first illustrate flash with the verbose output. To hide the output in the rendered HTML, you can use the `results = "hide"` chunk option (see [here](https://yihui.name/knitr/options)).

**Comment by willwerscheid** [comment]
In the first flash call the output is included. I could use `results = "hide"` for subsequent calls but that would require moving the commands that I do want output for (e.g., `c(const_elbo = fit_default$elbo, bycol_elbo = fit_var_bycol$elbo)`) and I'm not sure I agree that suppressing output via R Markdown is better than showing the user how to suppress it.

**Comment by pcarbo** [comment]
Okay.
