### ISSUE TITLE
Comparing factors from flash fits in vignettes

### ISSUE THREAD

**Issue by pcarbo** [willwerscheid/flashier#95]
It is often hard to compare the factor estimates from two calls to `plot()`. I find a simple scatterplot often more effective, e.g., this is what the scatterplot looks like comparing the "greedy" and "backfitting" results:

```r
plot(fit_greedy$F_pm,fit_backfit$F_pm,pch=20)
abline(a=0,b=1,col="magenta",lty="dotted")
```

![Screen Shot 2023-08-02 at 3 34 58 PM](https://github.com/willwerscheid/flashier/assets/1503904/0eb9051e-7acd-40d0-b33d-f507fc6354e4)

It is quite clear from the scatterplot that the factor estimates are mostly the same, except that the greedy fit is sparser. This difference is too subtle to notice by comparing the `plot()` outputs.

**Comment by willwerscheid** [comment]
what would you suggest? allowing the `plot` method to take more than one `flash` object?

**Comment by willwerscheid** [comment]
as is the `plot` method was not really designed for this purpose but we could think about what we would want to include if there were more than one `flash` object

**Comment by willwerscheid** [comment]
one challenge is that you need to match factors; often you will have the "same" factor but with different indices from one fit to another

**Comment by pcarbo** [comment]
I wasn't suggesting a change to the interface — just changes for the vignette(s).

**Comment by willwerscheid** [comment]
oh! my fault for not reading the title. sounds good, i will revise

**Comment by willwerscheid** [comment]
@pcarbo I may have closed this prematurely. could you please take a look at the updates to the intro vignette (the scatterplots) and let me know if they look ok to you?
