### ISSUE TITLE
Named outputs from sampler

### ISSUE THREAD

**Issue by pcarbo** [willwerscheid/flashier#96]
Would it be possible to name the outputs from a posterior sampler? This would make code more clear. For example, it would be nice if 

```r
factor3_samp <- lapply(samp, function(x) x[[2]][, 3])
```

could instead be written as

```r
factor3_samp <- lapply(samp, function(x) x$F[, 3])
```

**Comment by willwerscheid** [comment]
great idea! this was pretty straightforward to do. could you please update to latest version and confirm that it is now working for you?

**Comment by pcarbo** [comment]
Thanks, looks good.
