### ISSUE TITLE
Missing detail in help(ldf)

### ISSUE THREAD

**Issue by pcarbo** [willwerscheid/flashier#98]
@willwerscheid It isn't clear from `help(ldf)` that you are returning the matrix factorization as

```r
L %*% diag(D) %*% t(F)
```

That is, the `D` output is a vector and not a matrix.

**Comment by willwerscheid** [comment]
Just fixed now. Can you please take a look at commit ed195da5f7069eaf4255f4c58f0603851f04ae27 (0.2.55) before I close this?

**Comment by pcarbo** [comment]
Looks good, thanks!
